name: Qualys WAS Scan

on:
  push:
    branches:
      - main

jobs:
  qualys-was-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/upload-artifact@v3

      - name: Run Qualys WAS Scan
        uses: Qualys/github-action-qwas@main
        with:
          QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
          QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
          API_SERVER: ${{ vars.API_SERVER }}
          WEBAPP_ID: ${{ vars.WEBAPP_ID }}
          SCAN_NAME: ${{ vars.SCAN_NAME }}
          SCAN_TYPE: ${{ vars.SCAN_TYPE }}
